Build & Push to ECR

diff --git a/.github/workflows/deploy-infra b/.github/workflows/deploy-infra
--- a/.github/workflows/deploy-infra
+++ b/.github/workflows/deploy-infra
@@ -1,52 +1,69 @@
-name: Deploy Infrastructure
+name: Build and push to ECR
 
 on:
-  workflow_run:
-    workflows: ["Build and Push Docker Image"] # <- nombre definido en build-and-push.yml
-    types:
-      - completed
+  push:
+    branches:
+      - main
+
+env:
+  IMAGE_URI: 486166602683.dkr.ecr.us-east-1.amazonaws.com/techrepo:latest
+  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+  AWS_REGION: ${{ secrets.AWS_REGION }}
+  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} #486166602683.dkr.ecr.us-east-1.amazonaws.com
 
 jobs:
-  terraform:
+  build-and-push:
     runs-on: ubuntu-latest
-    needs: []
-
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-
+      - name: Checkout
+        uses: actions/checkout@v4
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      # Recuperar el artifact exportado en build-and-push.yml
-      - name: Download image URI artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: image-uri
+      - name: Login to ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+        
+      - name: Ensure ECR repository exists
+        run:  |
+          aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" || \
+          aws ecr create-repository --repository-name "$ECR_REPOSITORY" --region "$AWS_REGION"
+  
+      - name: Build, tag, and push image
+        env:
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+          IMAGE_TAG: latest
+        run: |
+          # Validar que el secret esté definido
+          if [ -z "$ECR_REPOSITORY" ]; then
+            echo "ERROR: ECR_REPOSITORY no está definido."
+            exit 1
+          fi
 
+          # Convertir nombre del repo a minúsculas
+          REPO_NAME=$(echo "$ECR_REPOSITORY" | tr '[:upper:]' '[:lower:]')
+          echo "Construyendo imagen Docker con repo: $REPO_NAME"
+
+          # Build de la imagen
+          docker build -t $REPO_NAME:$IMAGE_TAG -f ./docker/Dockerfile ./docker
+          # Tag para ECR
+          docker tag $REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
+          # Push a ECR
+          echo "Pushing image to ECR: $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG"
+          docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
+
+      #  Guardar URI 
+      - name: Save image URI to file
+        run: |
+          mkdir -p artifacts
+          echo "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest" > artifacts/image-uri.txt
+
+      # 4️⃣ Read the Docker image URI into an output variable
       - name: Read image URI
         id: image
         run: |
-          IMAGE_URI=$(cat image-uri.txt)
           echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.6.6
-
-      - name: Terraform Init
-        working-directory: terraform
-        run: terraform init
-
-      - name: Terraform Plan
-        working-directory: terraform
-        run: terraform plan -out=tfplan -var="docker_image_uri=${{ steps.image.outputs.image_uri }}"
-
-      - name: Terraform Apply
-        working-directory: terraform
-        run: terraform apply -auto-approve tfplan
